[project]
name = "asteroid-hazardousness-prediction"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Sahil Singh Chouhan", email = "sahilsinghchouhan2003@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.141.1",
    "ipykernel>=7.3.0",
    "joblib>=1.6.0",
    "numpy>=2.5.3",
    "pandas>=3.0.6",
    "pydantic>=2.13.5",
    "requests>=2.34.2",
    "scikit-learn>=1.9.1",
    "uvicorn>=0.53.0",
]

[project.scripts]
asteroid-hazardousness-prediction = "asteroid_hazardousness_prediction:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
